version: '3.8'

services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    command: ["/booking/docker/app.sh"]
    ports:
      - 7777:8000
    depends_on:
      - db
      - redis

  celery:
      build:
        context: .
      container_name: booking_celery
      command: ["/booking/docker/celery_flower.sh", "celery"]
      env_file:
        - .env-non-dev
      depends_on:
        - redis

  flower:
    build:
      context: .
    container_name: booking_flower
    command: [ "/booking/docker/celery_flower.sh", "flower" ]
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    ports:
      - 5555:5555
